version: "3"

services:
  db:
    container_name: btc_mysql
    image: mysql:8.0.31
    restart: always
    volumes:
      - 외부디렉터리:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "패스워드"
    privileged: true
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 외부포트:3306
